server:
  port: 8082


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


application:
  api:
    game-engine-service-api-client:
      baseurl: http://localhost:8081


spring:
  application:
    name: game-session-service
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:game-session-service
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
