server:
  port: 8083


spring:
  application:
    name: game-service-ui


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


application:
  api:
    game-session-service-api-client:
      baseurl: http://localhost:8082


vaadin:
  launch-browser: false
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.assignment.flamingo


logging:
  level:
    root: INFO
#    org.springframework.web: DEBUG
