create table tbl_moves (id serial generated by default as identity, session_id uuid not null, board_position enum ('A1','A2','A3','B1','B2','B3','C1','C2','C3') not null, player_symbol enum ('O','X') not null, primary key (id));
create table tbl_sessions (version integer, id uuid not null, game_status enum ('DRAW','INITIALIZED','IN_PROGRESS','WIN') not null, primary key (id));
alter table if exists tbl_moves add constraint FKmfildm62muu2cm1q1mmv9ey3a foreign key (session_id) references tbl_sessions;
